export const CALCULATE_DIFFERENCES_BETWEEN_POINTS = "CALCULATE_DIFFERENCES_BETWEEN_POINTS";
export const LINE_EXPRESSION = "LINE_EXPRESSION";
export const ADDING_POINT = "ADDING_POINT";
export const UPDATING_POINT = "UPDATING_POINT";
export const SET_CIRCLE_CENTER = "SET_CIRCLE_CENTER";
export const SET_AREA_RADIUS = "SET_AREA_RADIUS";
export const RESET_SHAPES = "RESET_SHAPES";